### ISSUE TITLE
Seperate Simulated Body interface in Planet struct

### ISSUE THREAD

**Issue by salwator** [salwator/gravity#1]
## Description

Provide interface for _Simulated Body_, that allows to get clone of object with position and speed changed.

Used to decouple simulation from celestial object implementation, cloning is essential for providing polymorphic construction interface for simulated bodies.

_Simulated Body_ interface is used ONLY for moving objects, does not provide mechanism for calculations.
## Tasks
- [x] extract Simulated Body interface
- [x] implement proper clone method in Planet struct
- [x] new type for Planet List - list of Simulated Body
- [ ] use of new list of Simulated Body in simulation
